products:
  - name: Small Parcel
    deliveryCharge: 4.50
  - name: Medium Box
    deliveryCharge: 8.75
  - name: Large Box
    deliveryCharge: 12.99
  - name: Envelope
    deliveryCharge: 2.99
  - name: Crate
    deliveryCharge: 20.00
  - name: Pallet
    deliveryCharge: 45.00


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: orders
    password: orders
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
